[package]
name = 'tomledit_r'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'tomleditR'

[dependencies]
extendr-api = { git = 'https://github.com/extendr/extendr' }
toml_edit = '0.19.11'