# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tomleditR_wrappers", use_symbols = TRUE, package_name = "tomleditR")

#' @docType package
#' @usage NULL
#' @useDynLib tomleditR, .registration = TRUE
NULL

inspect <- function(toml_doc) invisible(.Call(wrap__inspect, toml_doc))


# nolint end
