# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tomleditR_wrappers", use_symbols = TRUE, package_name = "tomleditR")

#' @docType package
#' @usage NULL
#' @useDynLib tomleditR, .registration = TRUE
NULL

#' Inspect a TOML document.
#' @param toml_doc A TOML document.
#' @export
inspect <- function(toml_doc) .Call(wrap__inspect, toml_doc)


# nolint end
