# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tomleditR_wrappers", use_symbols = TRUE, package_name = "tomleditR")

#' @docType package
#' @usage NULL
#' @useDynLib tomleditR, .registration = TRUE
NULL

#' Inspect a TOML document.
#' @param toml_doc A TOML document.
#' @export
inspect <- function(toml_doc) .Call(wrap__inspect, toml_doc)

#' Get a value from a TOML document.
#' @param toml_doc A TOML document.
#' @param key_path A path to the value.
#' @export
get_value <- function(toml_doc, key_path) .Call(wrap__get_value, toml_doc, key_path)

#' @export
TomlDocument <- new.env(parent = emptyenv())

TomlDocument$parse <- function(string) .Call(wrap__TomlDocument__parse, string)

TomlDocument$inspect <- function() .Call(wrap__TomlDocument__inspect, self)

TomlDocument$get <- function(key_path) .Call(wrap__TomlDocument__get, self, key_path)

#' @rdname TomlDocument
#' @usage NULL
#' @export
`$.TomlDocument` <- function (self, name) { func <- TomlDocument[[name]]; environment(func) <- environment(); func }

#' @export
`[[.TomlDocument` <- `$.TomlDocument`


# nolint end
